export const SHOP_PAGE = '/'
export const CREATE_AD_PAGE = '/creating'
export const PROFILE_PAGE = '/profile'
export const AD_PAGE = '/ad'
export const AUTH_PAGE = '/auth'
export const REGISTRATION_PAGE = '/registration'
export const NOT_FOUND_AD_PAGE = '/error'
export const ADMIN_PANEL = '/admin'