export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/'
export const FAVOURITES_ROUTE = '/favourites'
export const AD_ROUTE = '/ad'
export const ACCOUNT_ROUTE = '/account'